package com.example.composepoc.utils

import androidx.compose.ui.graphics.Color

const val BLUE = 0xFF0074AD
const val LIGHT_BLUE = 0xFFF2F8FB
const val LIGHT_GREY = 0xFFECEDEF
const val GREY = 0xFF677083
const val WHITE_COLOR = 0xFFFFFFFF
const val INKY = 0XFF0D1C3D
const val DIVIDER = 0xFFE9EBEE
const val RED_BADGE = 0xFFD00000
const val DEEP_BLUE = 0xFF003B71
const val MID_NIGHT = 0xFF003B71
const val SMOKE_WHITE = 0xFFB8B5B5
const val PINK_SHADE = 0xFF8F8B8B
const val PALE_BLUE = 0xFFF0F7FA
const val SHIMMER_GREY = 0xFF58616B
internal const val COLOR_COLO_BLUE_MILD = 0xFF0078B3
internal const val COLOR_PEBBLE = 0xFFF7F7F7
internal const val COLOR_DARK_GREY = 0xFF878F9B
internal const val COLOR_MEDIUM_PERSIAN_BLUE = 0xFF0269A3
internal const val COLOR_DARK_CERULEAN = 0xFF0269A3
internal const val COLOR_DELUGE = 0xFF816BAB
internal const val COLOR_DARK_SLATE_BLUE = 0xFF5D408A
internal const val COLOR_LIGHT_GREY = 0xFFEEEEEE
internal const val COLOR_BLACK = 0xFF000000
internal const val COLOR_BLUE_DEEP = 0xFF003B71
internal const val COLOR_GAINSBORO = 0xFFDDDDDD
internal const val COLOR_GREEN_MID = 0xFFEBF6EB
internal const val COLOR_OCEAN_BLUE = 0xFF057AC8
internal const val COLOR_BLUE_OPAQUE = 0xFFE6F2F7
internal const val COLOR_DOLPHIN_DARK = 0xFF8E8E93
internal const val COLOR_PERIGLACIAL_BLUE = 0xFFE5E5E5
internal const val COLOR_ROYAL_PURPLE = 0xFF5C33AA
internal const val COLOR_MEDIUM_PURPLE = 0xFF846EAD
const val PREVIEW_BACKGROUND_GRAY = 0x808080L
val Blue = Color(BLUE)
val LightBlue = Color(LIGHT_BLUE)
val LightGray = Color(LIGHT_GREY)
val Grey = Color(GREY)
val White = Color(WHITE_COLOR)
val Inky = Color(INKY)
val Divider = Color(DIVIDER)
val RedBadge = Color(RED_BADGE)
val DeepBlue = Color(DEEP_BLUE)
val MidNight = Color(MID_NIGHT)
val PaleBlue = Color(PALE_BLUE)
val Graphite = Color(DIVIDER)
val ColorDolphin: Color = Color(GREY)
val ColoBlueMild = Color(COLOR_COLO_BLUE_MILD)
val ColorPebble = Color(COLOR_PEBBLE)
val DarkGrey = Color(COLOR_DARK_GREY)
val MediumPersianBlue = Color(COLOR_MEDIUM_PERSIAN_BLUE)
val DarkCerulean = Color(COLOR_DARK_CERULEAN)
val ColorDeluge = Color(COLOR_DELUGE)
val ColorDarkSlateBlue = Color(COLOR_DARK_SLATE_BLUE)
val LightGrey = Color(COLOR_LIGHT_GREY)
val Black = Color(COLOR_BLACK)
val BlueDeep = Color(COLOR_BLUE_DEEP)
val Gainsboro = Color(COLOR_GAINSBORO)
val GreenMid = Color(COLOR_GREEN_MID)
val OceanBlue = Color(COLOR_OCEAN_BLUE)
val ColorBlueOpaque = Color(COLOR_BLUE_OPAQUE)
val ColorDolphinDark = Color(COLOR_DOLPHIN_DARK)
val PeriglacialBlue = Color(COLOR_PERIGLACIAL_BLUE)
val RoyalPurPle = Color(COLOR_ROYAL_PURPLE)
val MediumPurple = Color(COLOR_MEDIUM_PURPLE)